<?php

namespace Lorry\Model;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2015-06-12 at 12:51:38.
 */
class GameTest extends \PHPUnit_Framework_TestCase
{

    /**
     * @var Game
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->object = new Game;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {

    }

    /**
     * @covers Lorry\Model\Game::setShort
     * @todo   Implement testSetShort().
     */
    public function testSetShort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lorry\Model\Game::getShort
     * @todo   Implement testGetShort().
     */
    public function testGetShort()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lorry\Model\Game::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lorry\Model\Game::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lorry\Model\Game::getAddons
     * @todo   Implement testGetAddons().
     */
    public function testGetAddons()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lorry\Model\Game::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lorry\Model\Game::forApi
     * @todo   Implement testForApi().
     */
    public function testForApi()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Lorry\Model\Game::forPresenter
     * @todo   Implement testForPresenter().
     */
    public function testForPresenter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
