#!/usr/bin/env php
<?php
require 'bootstrap.php';

use Lorry\Command;
use Symfony\Component\Console\Application;

$application = new Application('Lorry');
$application->addCommands(array(
    new Command\CacheClearer, new Command\CacheWarmer,
    new Command\UserAdmin, new Command\UserMod, new Command\UserActivate
));
$application->run();
